[build]
  command = "npm run generate"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/"
  to = "/mapa"
  status = 302

[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200
